services:
  - type: web
    name: scraper-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: GROQ_API_KEY
        sync: false
    plan: free
